# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PointsToCatchments
                                 A QGIS plugin
 This plugin calculate the catchment for each point in a vector layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-03-09
        copyright            : (C) 2019 by Hans van der Kwast/IHE Delft
        email                : h.vanderkwast@un-ihe.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Hans van der Kwast/IHE Delft'
__date__ = '2019-03-09'
__copyright__ = '(C) 2019 by Hans van der Kwast/IHE Delft'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PointsToCatchments class from file PointsToCatchments.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .points_to_catchments import PointsToCatchmentsPlugin
    return PointsToCatchmentsPlugin()
