# -*- coding: utf-8 -*-

"""
/***************************************************************************
 PointsToCatchments
                                 A QGIS plugin
 This plugin calculate the catchment for each point in a vector layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-03-09
        copyright            : (C) 2019 by Hans van der Kwast/IHE Delft
        email                : h.vanderkwast@un-ihe.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Hans van der Kwast/IHE Delft'
__date__ = '2019-03-09'
__copyright__ = '(C) 2019 by Hans van der Kwast/IHE Delft'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from PyQt5.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFolderDestination,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterPoint,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterRasterDestination,
                       QgsVectorLayer,
                       QgsVectorFileWriter)
import os
import processing


class PointsToCatchmentsAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console. 

    OUTPUT = 'OUTPUT'
    OUTPUT_FOLDER = 'OUTPUT_FOLDER'
    INPUT_POINTS = 'INPUT_POINTS'
    INPUT_DEM = 'INPUT_DEM'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT_POINTS,
                self.tr('Outflow point layer')
            )
        )
        
        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT_DEM,
                self.tr('DEM layer')
            )
        )

        # # We add a feature sink in which to store our processed features (this
        # # usually takes the form of a newly created vector layer when the
        # # algorithm is run in QGIS).
        # self.addParameter(
            # QgsProcessingParameterRasterDestination(
                # self.OUTPUT,
                # self.tr('Output catchments layer')
            # )
        # )
        
        self.addParameter(QgsProcessingParameterFolderDestination(self.OUTPUT_FOLDER, self.tr("Output Folder"), None, False))

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        outflowPoints = self.parameterAsVectorLayer(parameters, self.INPUT_POINTS, context)
        #print(outflowPoints)
        #fileName, fileExtension = os.path.splitext(outflowPoints)
        inputDEM = self.parameterAsRasterLayer(parameters, self.INPUT_DEM, context)
        #fileNamePoints, fileExtensionPoints = os.path.splitext(outflowPoints)
        #fileNameDEM, fileExtensionDEM =os.path.splitext(inputDEM)
        #print (inputFile)
        out_folder = self.parameterAsString(parameters, self.OUTPUT_FOLDER, context)
        #Iterate over point features
        i = 0
        total = outflowPoints.featureCount()
        print('Iterate over', total, 'points')
        for outflowpoint in outflowPoints.getFeatures():
            i = i + 1
            #print(i)
    
            #Get x and y coordinate from point feature
            geom = outflowpoint.geometry()
            p = geom.asPoint()
            x = p.x()
            y = p.y()
            #print(x,y)
    
            # Calculate catchment raster from point feature
            catchraster = processing.run("saga:upslopearea", {'TARGET':None,
                                        'TARGET_PT_X':x,
                                        'TARGET_PT_Y':y,
                                        'ELEVATION':inputDEM,
                                        'SINKROUTE':None,
                                        'METHOD':0,'CONVERGE':1.1,
                                        'AREA': 'TEMPORARY_OUTPUT'})
            #Polygonize raster catchment
            catchpoly = processing.run("gdal:polygonize", {'INPUT':catchraster['AREA'],
                                        'BAND':1,
                                        'FIELD':'DN',
                                        'EIGHT_CONNECTEDNESS':False,
                                        'OUTPUT': 'TEMPORARY_OUTPUT'})
                                        
            catch_lyr = QgsVectorLayer(catchpoly['OUTPUT'], 'catchmments', 'ogr')
            catch_lyr.selectByExpression('"DN"=100')
            catch_filename = os.path.join(out_folder, 'area_{}'.format(i))
            QgsVectorFileWriter.writeAsVectorFormat(catch_lyr, catch_filename, onlySelected=True)
                                        
            # #Select feature with DN = 100
            # result = processing.run("native:extractbyattribute", {'INPUT':catchpoly['OUTPUT'],
                                    # 'FIELD':'DN',
                                    # 'OPERATOR':0,
                                    # 'VALUE':'100',
                                    # 'OUTPUT':'memory:'})
            #percentage = (i/total) * 100
            #print('%.1f' % percentage, '% done\r'),
            QgsProject.instance().addMapLayer(result['OUTPUT'])
        return 
        #{self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Calculate catchments from points'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Hydrology'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PointsToCatchmentsAlgorithm()
